export const SUPABASE_URL = "https://bhwwiyrxhvrscnhzvych.supabase.co"
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJod3dpeXJ4aHZyc2NuaHp2eWNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3MzM0NTgsImV4cCI6MjA4ODMwOTQ1OH0.6Cl-U5HuzFs2A7leRBBmz7514RtPEtCcWJLcUrbLnV4"
